### ISSUE TITLE
Kanban boards

### ISSUE THREAD

**Issue by Otegaa** [Otegaa/JS-Capstone-project#21]
### For this issue

- I have only one partner for this week so I deleted all cards C related to this project. My partner is a collaborator on this repository.
- https://github.com/Otegaa/JS-Capstone-project/projects/2
- My name is Ekiugbo Blessing and my partner's name is Mucha Julius Naibei
- The project link is https://github.com/Otegaa/JS-Capstone-project.git.

**Comment by brainconnect93** [comment]
## Status: Approved :heavy_check_mark:

Hi @team, 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## To Highlight 👍

- Kanban  properly Set up ✔️
- Task Equally assigned to member :heavy_check_mark: 

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
